up:
  - go: 1.10.1
  - golang_dep
  - homebrew:
    - golangci/tap/golangci-lint

commands:
  test:
    desc: Run the unittests
    run: go test -v

  lint:
    desc: Lint the project
    run: golangci-lint run
